name: project env 
channels:
  - defaults
dependencies:
  - python=3.8 # Or any version you prefer
  - pip
  - pip:
    - apache-airflow==2.2.0
    - boto3
    - requests
    - beautifulsoup4
    - python-csv # This is included in the Python standard library, so no need to install it separately
