name: Setup Airflow

on: [push]

jobs:
  setup-airflow:
    runs-on: ubuntu-latest
    env:
      AIRFLOW_HOME: ${{ github.workspace }}/airflow

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Apache Airflow
      run: pip install apache-airflow==2.2.0

    - name: Initialize Airflow Database
      run: airflow db init

    - name: Create Airflow User
      run: |
        airflow users create \
          --username ${{ secrets.AIRFLOW_USERNAME }} \
          --password ${{ secrets.AIRFLOW_PASSWORD }} \
          --firstname ${{ secrets.AIRFLOW_FIRSTNAME }} \
          --lastname ${{ secrets.AIRFLOW_LASTNAME }} \
          --role ${{ secrets.AIRFLOW_ROLE }} \
          --email ${{ secrets.AIRFLOW_EMAIL }}

    - name: Start Airflow Webserver
      run: |
        airflow webserver --port 8080 --daemon

    - name: Start Airflow Scheduler
      run: |
        airflow scheduler --daemon

    - name: Give Airflow Webserver and Scheduler time to start
      run: sleep 30

    # Here you can add steps to run tests or any other checks you need

    - name: Shutdown Airflow
      if: always()
      run: |
        airflow db check
        pkill -f "airflow scheduler"
        pkill -f "airflow webserver"
